version: "3.4"
services:
  quapsim:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      echo start
      && python3 run_ga_experiment.py -cs 500 -mr 100 -s 0 -t caching_enabled
      && python3 run_ga_experiment.py -cs 0 -mr 100 -s 0 -t no_caching
      && python3 run_ga_experiment.py -cs 500 -mr 100 -s 1 -t caching_enabled
      && python3 run_ga_experiment.py -cs 0 -mr 100 -s 1 -t no_caching
      && python3 run_ga_experiment.py -cs 500 -mr 100 -s 2 -t caching_enabled
      && python3 run_ga_experiment.py -cs 0 -mr 100 -s 2 -t no_caching
      && python3 run_ga_experiment.py -cs 500 -mr 100 -s 3 -t caching_enabled
      && python3 run_ga_experiment.py -cs 0 -mr 100 -s 3 -t no_caching
      && python3 run_ga_experiment.py -cs 500 -mr 100 -s 4 -t caching_enabled
      && python3 run_ga_experiment.py -cs 0 -mr 100 -s 4 -t no_caching
      "
    volumes:
      - ./:/app/
